services:
  - type: worker
    name: sm-todo-bot
    runtime: node
    plan: free
    buildCommand: npm install --omit=dev
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
